server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api-email
    username: postgres
    password: vini4222
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

# Adicionando configuração do emailsmtp

  mail:
    host: smtp.gmail.com
    port: 587
    username: emailestudospring@gmail.com
    password: ryapnhgtgupnmncl

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
